-- MySQL Script generated by MySQL Workbench
-- 05/11/16 21:39:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema RC2S
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `RC2S` ;

-- -----------------------------------------------------
-- Schema RC2S
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RC2S` DEFAULT CHARACTER SET utf8 ;
USE `RC2S` ;

-- -----------------------------------------------------
-- Table `RC2S`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RC2S`.`user` ;

CREATE TABLE IF NOT EXISTS `RC2S`.`user` (
  `id` INT(7) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `activated` TINYINT(1) NOT NULL DEFAULT 0,
  `locked` TINYINT(1) NOT NULL DEFAULT 0,
  `last_login` DATETIME NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RC2S`.`size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RC2S`.`size` ;

CREATE TABLE IF NOT EXISTS `RC2S`.`size` (
  `id` INT(7) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `x` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `y` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `z` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RC2S`.`synchronization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RC2S`.`synchronization` ;

CREATE TABLE IF NOT EXISTS `RC2S`.`synchronization` (
  `id` INT(7) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RC2S`.`cube`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RC2S`.`cube` ;

CREATE TABLE IF NOT EXISTS `RC2S`.`cube` (
  `id` INT(7) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `ip` VARCHAR(256) NOT NULL,
  `color` ENUM('red', 'green', 'yellow') NOT NULL,
  `size` INT(7) UNSIGNED NOT NULL,
  `synchronization` INT(7) UNSIGNED NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cubes_sizes_idx` (`size` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_cube_synchronization1_idx` (`synchronization` ASC),
  CONSTRAINT `fk_cubes_sizes`
    FOREIGN KEY (`size`)
    REFERENCES `RC2S`.`size` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cube_synchronization1`
    FOREIGN KEY (`synchronization`)
    REFERENCES `RC2S`.`synchronization` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RC2S`.`link_cube_synchronization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RC2S`.`link_cube_synchronization` ;

CREATE TABLE IF NOT EXISTS `RC2S`.`link_cube_synchronization` (
  `cube` INT(7) UNSIGNED NOT NULL,
  `synchronization` INT(7) UNSIGNED NOT NULL,
  PRIMARY KEY (`cube`, `synchronization`),
  INDEX `fk_cube_has_synchronization_synchronization1_idx` (`synchronization` ASC),
  INDEX `fk_cube_has_synchronization_cube1_idx` (`cube` ASC),
  CONSTRAINT `fk_cube_has_synchronization_cube1`
    FOREIGN KEY (`cube`)
    REFERENCES `RC2S`.`cube` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cube_has_synchronization_synchronization1`
    FOREIGN KEY (`synchronization`)
    REFERENCES `RC2S`.`synchronization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RC2S`.`plugin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RC2S`.`plugin` ;

CREATE TABLE IF NOT EXISTS `RC2S`.`plugin` (
  `id` INT(7) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `version` VARCHAR(32) NOT NULL,
  `author` VARCHAR(64) NULL,
  `status` VARCHAR(16) NULL,
  `activated` TINYINT(1) NOT NULL DEFAULT 0,
  `access` VARCHAR(45) NOT NULL DEFAULT 'rc2s-usergrp',
  `created` DATETIME NOT NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RC2S`.`track`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RC2S`.`track` ;

CREATE TABLE IF NOT EXISTS `RC2S`.`track` (
  `id` INT(7) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user` INT(7) UNSIGNED NOT NULL,
  `path` VARCHAR(256) NOT NULL,
  `order` SMALLINT UNSIGNED NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_track_user1_idx` (`user` ASC),
  CONSTRAINT `fk_track_user1`
    FOREIGN KEY (`user`)
    REFERENCES `RC2S`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RC2S`.`link_user_synchronization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RC2S`.`link_user_synchronization` ;

CREATE TABLE IF NOT EXISTS `RC2S`.`link_user_synchronization` (
  `user` INT(7) UNSIGNED NOT NULL,
  `synchronization` INT(7) UNSIGNED NOT NULL,
  PRIMARY KEY (`user`, `synchronization`),
  INDEX `fk_synchronization_has_user_user1_idx` (`user` ASC),
  INDEX `fk_synchronization_has_user_synchronization1_idx` (`synchronization` ASC),
  CONSTRAINT `fk_synchronization_has_user_synchronization1`
    FOREIGN KEY (`synchronization`)
    REFERENCES `RC2S`.`synchronization` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_synchronization_has_user_user1`
    FOREIGN KEY (`user`)
    REFERENCES `RC2S`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RC2S`.`log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RC2S`.`log` ;

CREATE TABLE IF NOT EXISTS `RC2S`.`log` (
  `id` INT(7) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` ENUM('INFO', 'WARN', 'ERROR', 'FATAL') NOT NULL DEFAULT 'INFO',
  `message` TEXT NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RC2S`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RC2S`.`group` ;

CREATE TABLE IF NOT EXISTS `RC2S`.`group` (
  `id` INT(7) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RC2S`.`link_user_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RC2S`.`link_user_group` ;

CREATE TABLE IF NOT EXISTS `RC2S`.`link_user_group` (
  `user` INT(7) UNSIGNED NOT NULL,
  `group` INT(7) UNSIGNED NOT NULL,
  PRIMARY KEY (`user`, `group`),
  INDEX `fk_user_has_groups_groups1_idx` (`group` ASC),
  INDEX `fk_user_has_groups_user1_idx` (`user` ASC),
  CONSTRAINT `fk_user_has_groups_user1`
    FOREIGN KEY (`user`)
    REFERENCES `RC2S`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_groups_groups1`
    FOREIGN KEY (`group`)
    REFERENCES `RC2S`.`group` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RC2S`.`token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RC2S`.`token` ;

CREATE TABLE IF NOT EXISTS `RC2S`.`token` (
  `id` INT(7) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user` INT(7) UNSIGNED NOT NULL,
  `token_client` VARCHAR(40) NULL,
  `token_server` VARCHAR(40) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idtoken_UNIQUE` (`id` ASC),
  INDEX `fk_token_user1_idx` (`user` ASC),
  CONSTRAINT `fk_token_user1`
    FOREIGN KEY (`user`)
    REFERENCES `RC2S`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO rc2sAdmin;
 DROP USER rc2sAdmin;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'rc2sAdmin' IDENTIFIED BY 'rc2sAdmin';

GRANT ALL ON `RC2S`.* TO 'rc2sAdmin';
SET SQL_MODE = '';
GRANT USAGE ON *.* TO rc2sUser;
 DROP USER rc2sUser;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'rc2sUser' IDENTIFIED BY 'rc2sUser';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `RC2S`.* TO 'rc2sUser';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
